name: Create new Release

on:
  pull_request: true
  push:
    branches:
      - master
    paths-ignore:
      - 'composer.json'
      - 'package.json'
      - 'CHANGELOG.md'
jobs:
    test:
        runs-on: ubuntu-latest

        strategy:
            max-parallel: 2
            matrix:
                php-versions: [7.3, 7.4]

        name: Test on PHP ${{ matrix.php-versions }}
        steps:
            -
                uses: actions/checkout@v2

            -
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-versions }}
                    extensions: intl, mbstring

            -
                name: Cache composer dependencies
                uses: actions/cache@v1
                with:
                    path: ~/.composer/cache
                    key: php-${{ matrix.php-versions }}-composer-${{ hashFiles('composer.lock') }}

            -
                name: Install composer dependencies
                run: composer install

            -
                name: Run PHPunit
                run: composer run test-cover-clover

            -
                name: Upload coverage to Codecov
                uses: codecov/codecov-action@v1
                # PHPUnit Coverage is broken on PHP7.3
                if: matrix.php-versions == '7.4'
                with:
                    token: ${{ secrets.CODECOV_TOKEN }}
                    file: ./Tests/Coverage.xml

    documentation:
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        runs-on: ubuntu-latest
        needs: test
        steps:
            -
                uses: actions/checkout@v1
            -
                name: vuepress-deploy
                uses: jenkey2011/vuepress-deploy@master
                env:
                    CNAME: configuration.neunerlei.eu
                    ACCESS_TOKEN: ${{ secrets.ACTIONS_DEPLOY_TOKEN }}
                    TARGET_BRANCH: gh-pages
                    BUILD_SCRIPT: cd docs && npm i && npm run build
                    BUILD_DIR: .vuepress/dist/

    release:
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        runs-on: ubuntu-latest
        needs: test
        steps:
            -
                uses: actions/checkout@v1
            -
                name: Create Changelog and bump release version
                uses: labor-digital/conventional-release-action@master
                with:
                    github-token: ${{ secrets.github_token }}

